# openapi-definition.yaml
swagger: "2.0"
info:
  title: OKR-tracker API
  description: Serverless APIs with API Gateway
  version: 1.0.0
  contact:
    name: Visualiseringsteamet
    url: https://okr.oslo.systems
    email: aulon.mujaj@origo.oslo.kommune.no
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
schemes:
 - https
produces:
 - application/json
paths:
  /kpi/{id}:
      get:
        summary: Get KPI
        operationId: getKPI
        x-google-backend:
          address: https://<location>-<project-id>.cloudfunctions.net/<CF-location>
          path_translation: APPEND_PATH_TO_ADDRESS
          protocol: h2
        security:
        - api_key: []
        parameters:
          - name: id
            in: path
            description: KPI Id
            required: true
            type: string
        responses:
          '200':
            description: A successful response
            schema:
              $ref: '#/definitions/Kpi'
          '404':
            description: KPI not found
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 404
                message:
                  type: string
          '500':
            description: Something went wrong
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 500
                message:
                  type: string
      post:
        summary: Post KPI progression.
        operationId: postKPI
        x-google-backend:
          address: https://<location>-<project-id>.cloudfunctions.net/<CF-location>
          path_translation: APPEND_PATH_TO_ADDRESS
          protocol: h2
        security:
        - api_key: []
        parameters:
          - name: id
            in: path
            description: KPI Id
            required: true
            type: string
          - name: progress
            in: body
            required: true
            description: updated progress
            schema:
              type: number
              example:
                progress: 123
        responses:
          '200':
            description: A successful response
            schema:
              type: string
              example: "Updated KPI (${id}) with progress: ${progress}"
          '404':
            description: KPI not found
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 404
                message:
                  type: string
          '400':
            description: A bad request
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 400
                message:
                  type: string
          '500':
            description: Something went wrong
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 500
                message:
                  type: string
  /keyres/{id}:
      get:
        summary: Get key result
        operationId: getKeyRes
        x-google-backend:
          address: https://<location>-<project-id>.cloudfunctions.net/<CF-location>
          path_translation: APPEND_PATH_TO_ADDRESS
          protocol: h2
        security:
        - api_key: []
        parameters:
          - name: id
            in: path
            description: Key result Id
            required: true
            type: string
        responses:
          '200':
            description: A successful response
            schema:
              $ref: '#/definitions/Keyres'
          '404':
            description: KPI not found
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 404
                message:
                  type: string
          '500':
            description: Something went wrong
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 500
                message:
                  type: string
      post:
        summary: Post Key result progression.
        operationId: postKeyRes
        x-google-backend:
          address: https://<location>-<project-id>.cloudfunctions.net/<CF-location>
          path_translation: APPEND_PATH_TO_ADDRESS
          protocol: h2
        security:
        - api_key: []
        parameters:
          - name: id
            in: path
            description: Key res Id
            required: true
            type: string
          - name: progress
            in: body
            required: true
            description: updated progress
            schema:
              type: number
              example:
                progress: 123
        responses:
          '200':
            description: A successful response
            schema:
              type: string
              example: "Updated Key result (${id}) with progress: ${progress}"
          '404':
            description: KPI not found
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 404
                message:
                  type: string
          '400':
            description: A bad request
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 400
                message:
                  type: string
          '500':
            description: Something went wrong
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 500
                message:
                  type: string


securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"

definitions:
  Keyres:
    properties:
      currentValue:
        type: number
      progression:
        type: number
      description:
        type: string
      created:
        type: string
        format: date-time
      edited:
        type: string
        format: date-time
      createdBy:
        type: string
      editedBy:
        type: string
      lastUpdated:
        type: object
        properties:
          value:
            type: number
          timestamp:
            type: string
            format: date-time
          comment:
            type: string
          createdBy:
            type: string
  Kpi:
    properties:
      currentValue:
        type: number
      name:
        type: string
      type:
        type: string
      created:
        type: string
        format: date-time
      edited:
        type: string
        format: date-time
      createdBy:
        type: string
      editedBy:
        type: string
      lastUpdated:
        type: object
        properties:
          value:
            type: number
          timestamp:
            type: string
            format: date-time
