const CONTRIBUTOR_TAG_COLORS = [
  'color-disabled',
  'color-green-dark',
  'color-hover',
  'color-blue',
  'color-beige-dark',
  'color-blue-dark-40',
  'color-blue-light',
  'color-yellow-80',
  'color-red-20',
  'color-focus',
  'color-green-dark-15',
  'color-yellow',
  'color-red-100',
  'color-blue-40',
  'color-focus',
  'color-green-40',
  'color-blue-dark',
  'color-blue-dark-15',
  'color-yellow-50',
  'color-green',
  'color-red',
];

export default CONTRIBUTOR_TAG_COLORS;
