name: "OpenAPI validation"

on:
  push:
    branches: [main]
    paths:
      - public/openapi.yaml
      - .github/workflows/validate-openapi.yml
  pull_request:
    branches: [main]
    paths:
      - public/openapi.yaml
      - .github/workflows/validate-openapi.yml
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: OpenAPI definition validation

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Validate OpenAPI definition
        run: npx --yes @redocly/cli@2.57.0 lint public/openapi.yaml
