name: "OpenAPI validation"

on:
  push:
    branches: [main]
    paths:
      - public/openapi.yaml
  pull_request:
    branches: [main]
    paths:
      - public/openapi.yaml
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: OpenAPI definition validation

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Validate OpenAPI definition
        uses: swaggerexpert/swagger-editor-validate@264fd875d3c6e1bf65da1f0a63e095cbe41ffef3 # v1.5.1
        with:
          definition-file: public/openapi.yaml
